from fastapi import APIRouter, HTTPException
from app.models import Technology

router = APIRouter()

technologies_db = [
    Technology(id="python", name="Python", category="Programming Languages",
               description="A high-level, general-purpose programming language known for its readability and versatility.",
               difficulty="Beginner", learningTime="3-6 months", prerequisites=[], skills=["Syntax", "OOP", "Libraries", "Debugging"],
               applications=["Web Development", "Data Science", "AI/ML", "Automation"],
               companies=["Google", "Netflix", "Spotify", "Instagram"],
               futureOutlook="Growing", growthRate=95, popularity=98, icon="🐍", color="#3776AB"),
    Technology(id="javascript", name="JavaScript", category="Programming Languages",
               description="A dynamic programming language essential for web development.",
               difficulty="Beginner", learningTime="3-6 months", prerequisites=[], skills=["DOM", "Async", "ES6+"],
               applications=["Web Development", "Mobile Apps", "Server-side"],
               companies=["Google", "Meta", "Microsoft", "Amazon"],
               futureOutlook="Growing", growthRate=90, popularity=97, icon="🟨", color="#F7DF1E"),
    Technology(id="typescript", name="TypeScript", category="Programming Languages",
               description="A typed superset of JavaScript that compiles to plain JavaScript.",
               difficulty="Intermediate", learningTime="2-4 months", prerequisites=["javascript"], 
               skills=["Types", "Generics", "Interfaces", "Decorators"],
               applications=["Web Development", "Enterprise Apps", "Libraries"],
               companies=["Microsoft", "Google", "Airbnb", "Slack"],
               futureOutlook="Growing", growthRate=92, popularity=90, icon="🔷", color="#3178C6"),
    Technology(id="machine-learning", name="Machine Learning", category="Artificial Intelligence",
               description="A subset of AI that enables systems to learn and improve from experience.",
               difficulty="Advanced", learningTime="6-12 months", prerequisites=["python", "mathematics", "statistics"],
               skills=["Regression", "Classification", "Clustering", "Model Evaluation"],
               applications=["Predictive Analytics", "Recommendation Systems", "Fraud Detection"],
               companies=["Google", "Amazon", "Microsoft", "Apple", "Meta"],
               futureOutlook="Growing", growthRate=98, popularity=95, icon="🤖", color="#FF6F00"),
    Technology(id="deep-learning", name="Deep Learning", category="Artificial Intelligence",
               description="A subset of machine learning using neural networks with many layers.",
               difficulty="Advanced", learningTime="6-12 months", prerequisites=["machine-learning", "python", "linear-algebra"],
               skills=["Neural Networks", "CNNs", "RNNs", "Transformers"],
               applications=["Image Recognition", "NLP", "Speech Recognition", "Generative AI"],
               companies=["Google DeepMind", "OpenAI", "Meta AI", "NVIDIA"],
               futureOutlook="Growing", growthRate=99, popularity=93, icon="🧠", color="#E91E63"),
    Technology(id="computer-vision", name="Computer Vision", category="Artificial Intelligence",
               description="A field of AI that enables computers to interpret and understand visual information.",
               difficulty="Advanced", learningTime="6-12 months", prerequisites=["deep-learning", "python", "linear-algebra"],
               skills=["Image Processing", "Object Detection", "Segmentation", "Feature Extraction"],
               applications=["Autonomous Vehicles", "Medical Imaging", "Surveillance", "AR/VR"],
               companies=["Tesla", "Waymo", "NVIDIA", "Microsoft", "Apple"],
               futureOutlook="Growing", growthRate=94, popularity=85, icon="👁️", color="#9C27B0"),
    Technology(id="natural-language-processing", name="Natural Language Processing", category="Artificial Intelligence",
               description="A branch of AI that helps computers understand, interpret, and generate human language.",
               difficulty="Advanced", learningTime="4-8 months", prerequisites=["machine-learning", "python"],
               skills=["Tokenization", "Embeddings", "Transformers", "Sequence Models"],
               applications=["Chatbots", "Translation", "Sentiment Analysis", "Text Generation"],
               companies=["OpenAI", "Google", "Meta", "Amazon", "IBM"],
               futureOutlook="Growing", growthRate=97, popularity=90, icon="💬", color="#00BCD4"),
    Technology(id="llm-engineering", name="LLM Engineering", category="Artificial Intelligence",
               description="The practice of building applications around Large Language Models.",
               difficulty="Advanced", learningTime="3-6 months", prerequisites=["python", "natural-language-processing", "machine-learning"],
               skills=["Prompt Engineering", "RAG", "Fine-tuning", "LangChain"],
               applications=["Chatbots", "Code Generation", "Content Creation"],
               companies=["OpenAI", "Anthropic", "Google", "Meta"],
               futureOutlook="Growing", growthRate=100, popularity=96, icon="📝", color="#FF5722"),
    Technology(id="docker", name="Docker", category="DevOps & Cloud",
               description="A platform for developing, shipping, and running applications in containers.",
               difficulty="Intermediate", learningTime="1-2 months", prerequisites=["linux", "networking"],
               skills=["Containerization", "Dockerfile", "Compose", "Registry"],
               applications=["Microservices", "CI/CD", "DevOps", "Cloud Deployments"],
               companies=["Netflix", "Uber", "Spotify", "Airbnb"],
               futureOutlook="Growing", growthRate=88, popularity=92, icon="🐳", color="#2496ED"),
    Technology(id="kubernetes", name="Kubernetes", category="DevOps & Cloud",
               description="An open-source platform for automating deployment, scaling, and management of containerized applications.",
               difficulty="Advanced", learningTime="3-6 months", prerequisites=["docker", "linux", "networking", "cloud-computing"],
               skills=["Orchestration", "Pods", "Services", "Helm"],
               applications=["Microservices", "Cloud Native", "CI/CD", "Edge Computing"],
               companies=["Google", "Spotify", "Adobe", "Capital One"],
               futureOutlook="Growing", growthRate=91, popularity=90, icon="☸️", color="#326CE5"),
    Technology(id="cloud-computing", name="Cloud Computing", category="DevOps & Cloud",
               description="The delivery of computing services over the internet.",
               difficulty="Intermediate", learningTime="3-6 months", prerequisites=["networking"],
               skills=["IaaS", "PaaS", "SaaS", "Virtualization"],
               applications=["Web Hosting", "Data Storage", "SaaS", "Disaster Recovery"],
               companies=["AWS", "Microsoft", "Google", "IBM", "Oracle"],
               futureOutlook="Growing", growthRate=93, popularity=94, icon="☁️", color="#4285F4"),
    Technology(id="aws", name="AWS", category="DevOps & Cloud",
               description="Amazon Web Services is the world's most comprehensive cloud platform.",
               difficulty="Intermediate", learningTime="3-6 months", prerequisites=["cloud-computing", "networking"],
               skills=["EC2", "S3", "Lambda", "RDS"],
               applications=["Web Hosting", "Big Data", "AI/ML", "IoT"],
               companies=["Netflix", "Airbnb", "Spotify", "Samsung", "Unilever"],
               futureOutlook="Growing", growthRate=89, popularity=95, icon="☁️", color="#FF9900"),
    Technology(id="cybersecurity", name="Cybersecurity", category="Security",
               description="The practice of protecting systems, networks, and programs from digital attacks.",
               difficulty="Intermediate", learningTime="6-12 months", prerequisites=["networking", "linux"],
               skills=["Network Security", "Cryptography", "Ethical Hacking", "Incident Response"],
               applications=["Network Protection", "Penetration Testing", "Compliance"],
               companies=["CrowdStrike", "Palo Alto Networks", "Fortinet", "IBM", "Cisco"],
               futureOutlook="Growing", growthRate=96, popularity=91, icon="🔒", color="#DC143C"),
    
    Technology(id="react", name="React", category="Programming Languages",
               description="A JavaScript library for building user interfaces.",
               difficulty="Intermediate", learningTime="3-6 months", prerequisites=["javascript", "typescript"],
               skills=["Components", "Hooks", "State Management", "JSX"],
               applications=["Web Apps", "Mobile (React Native)", "SPAs"],
               companies=["Meta", "Netflix", "Airbnb", "Uber"],
               futureOutlook="Growing", growthRate=87, popularity=94, icon="⚛️", color="#61DAFB"),
    Technology(id="sql", name="SQL", category="Data & Analytics",
               description="Structured Query Language for managing and querying relational databases.",
               difficulty="Beginner", learningTime="1-2 months", prerequisites=[],
               skills=["Queries", "Joins", "Indexing"],
               applications=["Backend", "Data Analysis", "BI", "Reporting"],
               companies=["Every Tech Company"],
               futureOutlook="Stable", growthRate=80, popularity=93, icon="🗄️", color="#336791"),
    Technology(id="git", name="Git", category="DevOps & Cloud",
               description="A distributed version control system for tracking changes in source code.",
               difficulty="Beginner", learningTime="1 month", prerequisites=[],
               skills=["Version Control", "Branching", "Merging", "Rebasing"],
               applications=["Software Development", "Open Source", "CI/CD", "Documentation"],
               companies=["Every Tech Company"],
               futureOutlook="Stable", growthRate=75, popularity=96, icon="📦", color="#F05032"),
    Technology(id="rag", name="RAG (Retrieval Augmented Generation)", category="Artificial Intelligence",
               description="A technique that combines information retrieval with text generation.",
               difficulty="Advanced", learningTime="2-4 months", prerequisites=["llm-engineering", "python", "natural-language-processing"],
               skills=["Vector DBs", "Embeddings", "Chunking", "Retrieval"],
               applications=["Q&A Systems", "Research Tools", "Customer Support", "Document Analysis"],
               companies=["OpenAI", "Anthropic", "Cohere", "LlamaIndex"],
               futureOutlook="Growing", growthRate=98, popularity=88, icon="🔍", color="#8BC34A"),
    Technology(id="quantum-computing", name="Quantum Computing", category="Emerging Technologies",
               description="An emerging field that uses quantum mechanics to process information.",
               difficulty="Advanced", learningTime="12-24 months", prerequisites=["linear-algebra", "mathematics"],
               skills=["Quantum Gates", "Qubits", "Quantum Algorithms", "Error Correction"],
               applications=["Cryptography", "Drug Discovery", "Optimization", "Financial Modeling"],
               companies=["IBM", "Google", "Microsoft", "IonQ", "Rigetti"],
               futureOutlook="Growing", growthRate=88, popularity=65, icon="⚛️", color="#00BCD4"),
    Technology(id="blockchain", name="Blockchain", category="Emerging Technologies",
               description="A distributed ledger technology that maintains records linked using cryptography.",
               difficulty="Advanced", learningTime="3-6 months", prerequisites=["networking", "cybersecurity"],
               skills=["Smart Contracts", "Consensus", "DApps", "Web3"],
               applications=["Cryptocurrency", "Supply Chain", "Identity", "Voting"],
               companies=["Ethereum", "Chainlink", "IBM", "Microsoft"],
               futureOutlook="Stable", growthRate=72, popularity=68, icon="⛓️", color="#F7931A"),
    Technology(id="prompt-engineering", name="Prompt Engineering", category="Artificial Intelligence",
               description="The practice of designing and optimizing input prompts to get desired outputs from LLMs.",
               difficulty="Beginner", learningTime="1-2 months", prerequisites=[],
               skills=["Prompt Design", "Chain-of-Thought", "Few-shot", "Persona Setting"],
               applications=["Content Generation", "Code Generation", "Chatbots", "Data Extraction"],
               companies=["OpenAI", "Anthropic", "Google", "Meta", "Microsoft"],
               futureOutlook="Growing", growthRate=96, popularity=89, icon="✏️", color="#FF9800"),
    Technology(id="data-engineering", name="Data Engineering", category="Data & Analytics",
               description="The practice of designing and building systems for collecting and storing data at scale.",
               difficulty="Intermediate", learningTime="4-8 months", prerequisites=["python", "sql", "cloud-computing"],
               skills=["ETL", "Data Pipelines", "Data Warehousing", "Spark"],
               applications=["Analytics", "Business Intelligence", "ML Infrastructure", "Reporting"],
               companies=["Amazon", "Google", "Meta", "Netflix", "Uber"],
               futureOutlook="Growing", growthRate=91, popularity=86, icon="🏗️", color="#795548"),
    Technology(id="ci-cd", name="CI/CD", category="DevOps & Cloud",
               description="Continuous Integration and Continuous Deployment practices for automated testing and deployment.",
               difficulty="Intermediate", learningTime="1-3 months", prerequisites=["git", "docker"],
               skills=["Pipeline Design", "Automation", "Testing", "Deployment"],
               applications=["DevOps", "Software Delivery", "Quality Assurance", "Release Management"],
               companies=["GitHub", "GitLab", "Netflix", "Google", "Amazon"],
               futureOutlook="Growing", growthRate=86, popularity=87, icon="🔄", color="#E91E63"),
]

@router.get("", response_model=list[Technology])
async def get_all_technologies():
    return technologies_db

@router.get("/{tech_id}", response_model=Technology)
async def get_technology(tech_id: str):
    tech = next((t for t in technologies_db if t.id == tech_id), None)
    if not tech:
        raise HTTPException(status_code=404, detail="Technology not found")
    return tech

@router.get("/category/{category}")
async def get_technologies_by_category(category: str):
    return [t for t in technologies_db if t.category.lower() == category.lower()]

@router.get("/search/{query}")
async def search_technologies(query: str):
    q = query.lower()
    return [t for t in technologies_db if q in t.name.lower() or q in t.description.lower() or q in t.category.lower()]
