from sqlalchemy.orm import Session
from app.models.models import User, Technology, Relationship, Career, Trend, ResearchPaper
from app.core.security import get_password_hash


def seed_database(db: Session):
    if db.query(Technology).count() > 0:
        return

    db.add(User(username="admin", email="admin@atin.com", hashed_password=get_password_hash("admin123"), is_active=True, is_admin=True))
    db.commit()

    techs = [
        Technology(slug="python", name="Python", category="Programming Languages", description="Python is a versatile, high-level programming language known for its readability and extensive ecosystem.", difficulty="Beginner", learning_time="2-3 months", prerequisites=["Basic computer literacy"], skills=["Syntax & fundamentals", "OOP", "Libraries (NumPy, Pandas)", "Web frameworks", "Testing"], applications=["Web development", "Data science", "Machine learning", "Automation", "Scripting"], companies=["Google", "Meta", "Netflix", "Spotify", "Instagram"], future_outlook="Growing", growth_rate=95, popularity=98, icon="", color="#3776AB"),
        Technology(slug="javascript", name="JavaScript", category="Programming Languages", description="JavaScript is the language of the web, powering interactive frontends and scalable backends.", difficulty="Beginner", learning_time="3-6 months", prerequisites=["Basic HTML/CSS"], skills=["ES6+ syntax", "DOM manipulation", "Async programming", "Frameworks (React/Vue)", "Node.js"], applications=["Web development", "Mobile apps", "Desktop apps", "Serverless", "Real-time apps"], companies=["Google", "Meta", "Microsoft", "Apple", "Amazon"], future_outlook="Growing", growth_rate=90, popularity=97, icon="", color="#F7DF1E"),
        Technology(slug="typescript", name="TypeScript", category="Programming Languages", description="TypeScript adds static typing to JavaScript, catching errors at compile time.", difficulty="Intermediate", learning_time="3-6 months", prerequisites=["JavaScript"], skills=["Type system", "Generics", "Interfaces & types", "Decorators", "Module system"], applications=["Web apps", "Enterprise software", "Library development", "Full-stack development", "API development"], companies=["Microsoft", "Google", "Airbnb", "Asana", "Slack"], future_outlook="Growing", growth_rate=92, popularity=93, icon="", color="#3178C6"),
        Technology(slug="react", name="React", category="Frontend Development", description="React is a declarative, component-based library for building user interfaces.", difficulty="Intermediate", learning_time="3-6 months", prerequisites=["JavaScript", "HTML/CSS"], skills=["Components & props", "Hooks", "State management", "Routing", "Performance optimization"], applications=["Single-page apps", "E-commerce", "Social media", "Dashboards", "Mobile (React Native)"], companies=["Meta", "Netflix", "Airbnb", "Uber", "Twitter"], future_outlook="Growing", growth_rate=88, popularity=94, icon="", color="#61DAFB"),
        Technology(slug="nodejs", name="Node.js", category="Backend Development", description="Node.js enables JavaScript on the server with event-driven, non-blocking I/O.", difficulty="Intermediate", learning_time="3-6 months", prerequisites=["JavaScript"], skills=["Express.js", "RESTful APIs", "Middleware", "Database integration", "Authentication"], applications=["API servers", "Microservices", "Real-time apps", "CLI tools", "Web sockets"], companies=["LinkedIn", "Netflix", "PayPal", "Uber", "Walmart"], future_outlook="Growing", growth_rate=85, popularity=92, icon="", color="#339933"),
        Technology(slug="machine-learning", name="Machine Learning", category="Artificial Intelligence", description="Machine Learning enables systems to learn and improve from experience.", difficulty="Advanced", learning_time="6-12 months", prerequisites=["Python", "Statistics", "Linear algebra"], skills=["Supervised learning", "Unsupervised learning", "Feature engineering", "Model evaluation", "Scikit-learn"], applications=["Recommendation systems", "Fraud detection", "Predictive analytics", "Image recognition", "NLP"], companies=["Google", "Amazon", "Microsoft", "Apple", "Netflix"], future_outlook="Growing", growth_rate=98, popularity=95, icon="", color="#FF6F00"),
        Technology(slug="deep-learning", name="Deep Learning", category="Artificial Intelligence", description="Deep Learning uses multi-layer neural networks to model complex patterns.", difficulty="Advanced", learning_time="6-12 months", prerequisites=["Machine learning", "Python", "Calculus"], skills=["Neural networks", "CNNs", "RNNs/Transformers", "TensorFlow/PyTorch", "GPU optimization"], applications=["Computer vision", "Speech recognition", "NLP", "Generative AI", "Autonomous vehicles"], companies=["Google DeepMind", "OpenAI", "Meta AI", "Tesla", "NVIDIA"], future_outlook="Growing", growth_rate=99, popularity=93, icon="", color="#E91E63"),
        Technology(slug="llm-engineering", name="LLM Engineering", category="Artificial Intelligence", description="LLM Engineering covers the lifecycle of large language models: prompt engineering, fine-tuning, RAG architectures.", difficulty="Advanced", learning_time="6-12 months", prerequisites=["Python", "Deep learning", "NLP basics"], skills=["Prompt engineering", "RAG architectures", "Vector databases", "Fine-tuning", "LLM evaluation"], applications=["Chatbots", "Code generation", "Content creation", "Document analysis", "Knowledge retrieval"], companies=["OpenAI", "Anthropic", "Google", "Microsoft", "Hugging Face"], future_outlook="Growing", growth_rate=100, popularity=96, icon="", color="#9C27B0"),
        Technology(slug="nlp", name="Natural Language Processing", category="Artificial Intelligence", description="NLP enables computers to understand, interpret, and generate human language.", difficulty="Advanced", learning_time="6-12 months", prerequisites=["Python", "Machine learning", "Linguistics basics"], skills=["Text preprocessing", "Word embeddings", "Sequence models", "Transformers", "Hugging Face"], applications=["Sentiment analysis", "Machine translation", "Text summarization", "NER", "Question answering"], companies=["Google", "Meta", "Amazon", "Microsoft", "OpenAI"], future_outlook="Growing", growth_rate=97, popularity=89, icon="", color="#4CAF50"),
        Technology(slug="computer-vision", name="Computer Vision", category="Artificial Intelligence", description="Computer Vision enables machines to interpret visual information using CNNs and vision transformers.", difficulty="Advanced", learning_time="6-12 months", prerequisites=["Python", "Deep learning", "Linear algebra"], skills=["Image processing", "CNNs", "Object detection (YOLO)", "Image segmentation", "OpenCV"], applications=["Autonomous vehicles", "Medical imaging", "Surveillance", "AR/VR", "Quality inspection"], companies=["Tesla", "Google", "Meta", "NVIDIA", "Waymo"], future_outlook="Growing", growth_rate=94, popularity=87, icon="", color="#FF5722"),
        Technology(slug="rag", name="RAG (Retrieval Augmented Generation)", category="Artificial Intelligence", description="RAG combines information retrieval with LLMs for accurate, context-aware responses.", difficulty="Advanced", learning_time="3-6 months", prerequisites=["Python", "LLM basics", "Vector databases"], skills=["Document chunking", "Embeddings", "Vector search", "Retrieval pipelines", "Evaluation"], applications=["Enterprise search", "Customer support", "Document QA", "Knowledge bases", "Research assistants"], companies=["OpenAI", "Anthropic", "Cohere", "LlamaIndex", "LangChain"], future_outlook="Growing", growth_rate=98, popularity=88, icon="", color="#00BCD4"),
        Technology(slug="prompt-engineering", name="Prompt Engineering", category="Artificial Intelligence", description="Prompt Engineering is the art of designing inputs to guide LLM outputs.", difficulty="Beginner", learning_time="1-2 months", prerequisites=["Basic AI concepts"], skills=["Chain-of-thought", "Few-shot learning", "Structured outputs", "Context management", "Evaluation"], applications=["Content generation", "Code assistance", "Data extraction", "Chatbots", "Automation"], companies=["OpenAI", "Anthropic", "Google", "Microsoft", "GitHub"], future_outlook="Growing", growth_rate=96, popularity=85, icon="", color="#FFC107"),
        Technology(slug="sql", name="SQL", category="Data & Analytics", description="SQL is the standard language for relational database management and data manipulation.", difficulty="Beginner", learning_time="1-3 months", prerequisites=["Basic data concepts"], skills=["SELECT queries", "JOINs", "Aggregations", "Indexing", "Normalization"], applications=["Data analysis", "Backend development", "Business intelligence", "Reporting", "ETL pipelines"], companies=["All tech companies"], future_outlook="Stable", growth_rate=80, popularity=93, icon="", color="#336791"),
        Technology(slug="docker", name="Docker", category="DevOps & Cloud", description="Docker containers package applications with all dependencies for consistent environments.", difficulty="Intermediate", learning_time="2-3 months", prerequisites=["Linux basics", "CLI familiarity"], skills=["Dockerfile syntax", "Image management", "Docker Compose", "Networking", "Registry management"], applications=["Microservices", "CI/CD pipelines", "Dev environments", "Cloud deployment", "Edge computing"], companies=["All tech companies"], future_outlook="Growing", growth_rate=88, popularity=92, icon="", color="#2496ED"),
        Technology(slug="kubernetes", name="Kubernetes", category="DevOps & Cloud", description="Kubernetes orchestrates containerized applications at scale.", difficulty="Advanced", learning_time="3-6 months", prerequisites=["Docker", "Networking", "Linux"], skills=["Pods & deployments", "Services & ingress", "Helm charts", "RBAC", "Cluster management"], applications=["Container orchestration", "Cloud-native apps", "Microservices", "Auto-scaling", "Service mesh"], companies=["Google", "Amazon", "Microsoft", "Spotify", "Uber"], future_outlook="Growing", growth_rate=90, popularity=90, icon="", color="#326CE5"),
        Technology(slug="aws", name="AWS", category="DevOps & Cloud", description="Amazon Web Services is the leading cloud platform with 200+ services.", difficulty="Intermediate", learning_time="6-12 months", prerequisites=["Networking", "Linux basics"], skills=["EC2 & S3", "Lambda", "RDS & DynamoDB", "IAM & security", "Cloud architecture"], applications=["Cloud hosting", "Serverless apps", "Data lakes", "Machine learning", "IoT"], companies=["Netflix", "Airbnb", "Lyft", "Slack", "Pinterest"], future_outlook="Growing", growth_rate=87, popularity=95, icon="", color="#FF9900"),
        Technology(slug="cloud-fundamentals", name="Cloud Computing", category="DevOps & Cloud", description="Cloud Computing covers IaaS, PaaS, SaaS models, deployment strategies, and architecture patterns.", difficulty="Intermediate", learning_time="3-6 months", prerequisites=["Networking basics"], skills=["Cloud models", "Virtualization", "Storage solutions", "Networking", "Security & compliance"], applications=["Infrastructure hosting", "Disaster recovery", "DevOps", "Big data", "AI/ML workloads"], companies=["All cloud providers"], future_outlook="Growing", growth_rate=85, popularity=94, icon="", color="#4285F4"),
        Technology(slug="git", name="Git", category="DevOps & Cloud", description="Git is the industry-standard version control system for collaboration and code management.", difficulty="Beginner", learning_time="1-2 months", prerequisites=["CLI basics"], skills=["Branching & merging", "Rebasing", "Pull requests", "Git workflows", "Conflict resolution"], applications=["Version control", "Collaboration", "CI/CD", "Open source", "Code review"], companies=["All tech companies"], future_outlook="Stable", growth_rate=75, popularity=96, icon="", color="#F05032"),
        Technology(slug="mlops", name="MLOps", category="DevOps & Cloud", description="MLOps applies DevOps principles to machine learning.", difficulty="Advanced", learning_time="3-6 months", prerequisites=["Machine learning", "DevOps", "Docker"], skills=["MLflow", "Model serving", "Feature stores", "Pipeline automation", "Model monitoring"], applications=["ML production", "Model governance", "A/B testing", "Model registry", "Automated retraining"], companies=["Google", "Netflix", "Uber", "Airbnb", "Microsoft"], future_outlook="Growing", growth_rate=95, popularity=82, icon="", color="#00BFA5"),
        Technology(slug="cybersecurity", name="Cybersecurity", category="Security", description="Cybersecurity protects systems, networks, and data from digital attacks.", difficulty="Advanced", learning_time="6-12 months", prerequisites=["Networking", "Operating systems"], skills=["Network security", "Cryptography", "Penetration testing", "Security analysis", "Incident response"], applications=["Network protection", "Data encryption", "Threat detection", "Compliance", "Security auditing"], companies=["CrowdStrike", "Palo Alto Networks", "Cloudflare", "Microsoft", "Google"], future_outlook="Growing", growth_rate=96, popularity=91, icon="", color="#DC2626"),
        Technology(slug="data-science", name="Data Science", category="Data & Analytics", description="Data Science combines statistics, programming, and domain expertise to extract insights from data.", difficulty="Intermediate", learning_time="6-12 months", prerequisites=["Python", "Statistics", "SQL"], skills=["Statistical analysis", "Data visualization", "Machine learning", "Big data tools", "Storytelling"], applications=["Business intelligence", "Predictive modeling", "Customer analytics", "Risk assessment", "Optimization"], companies=["Google", "Amazon", "Netflix", "Spotify", "Airbnb"], future_outlook="Growing", growth_rate=87, popularity=88, icon="", color="#1A237E"),
        Technology(slug="statistics", name="Statistics", category="Mathematics", description="Statistics provides the mathematical foundation for data analysis and machine learning.", difficulty="Intermediate", learning_time="3-6 months", prerequisites=["Basic mathematics"], skills=["Probability", "Hypothesis testing", "Regression", "Bayesian methods", "Experimental design"], applications=["Data analysis", "A/B testing", "Research", "Quality control", "Risk modeling"], companies=["All data-driven companies"], future_outlook="Stable", growth_rate=72, popularity=80, icon="", color="#3949AB"),
        Technology(slug="linear-algebra", name="Linear Algebra", category="Mathematics", description="Linear Algebra is fundamental to machine learning and deep learning.", difficulty="Intermediate", learning_time="2-3 months", prerequisites=["High school math"], skills=["Vectors & matrices", "Matrix operations", "Eigenvalues", "Vector spaces", "Linear transformations"], applications=["Machine learning", "Computer graphics", "Quantum computing", "Data science", "Optimization"], companies=["NVIDIA", "Google", "Meta", "DeepMind", "Intel"], future_outlook="Stable", growth_rate=70, popularity=75, icon="", color="#5E35B1"),
        Technology(slug="calculus", name="Calculus", category="Mathematics", description="Calculus provides the mathematical foundation for optimization in machine learning.", difficulty="Intermediate", learning_time="2-3 months", prerequisites=["High school math"], skills=["Derivatives", "Integrals", "Multivariable calculus", "Gradients", "Optimization"], applications=["Deep learning", "Physics simulations", "Economics", "Engineering", "Optimization"], companies=["NVIDIA", "Google", "Meta", "DeepMind", "Intel"], future_outlook="Stable", growth_rate=65, popularity=68, icon="", color="#8E24AA"),
        Technology(slug="rust", name="Rust", category="Programming Languages", description="Rust is a systems programming language focused on safety, speed, and concurrency.", difficulty="Advanced", learning_time="6-12 months", prerequisites=["C/C++ basics", "Systems programming"], skills=["Ownership & borrowing", "Lifetimes", "Traits", "Concurrency", "Unsafe Rust"], applications=["Systems programming", "WebAssembly", "CLI tools", "Embedded systems", "Game engines"], companies=["Mozilla", "Microsoft", "Google", "Amazon", "Meta"], future_outlook="Growing", growth_rate=85, popularity=78, icon="", color="#DEA584"),
        Technology(slug="go", name="Go", category="Programming Languages", description="Go is a statically typed, compiled language designed for simplicity and concurrency.", difficulty="Intermediate", learning_time="3-6 months", prerequisites=["Programming basics"], skills=["Concurrency (goroutines)", "Interfaces", "Error handling", "Standard library", "Testing"], applications=["Cloud services", "Microservices", "CLI tools", "DevOps tools", "Network servers"], companies=["Google", "Uber", "Twitch", "Dropbox", "Cloudflare"], future_outlook="Growing", growth_rate=84, popularity=81, icon="", color="#00ADD8"),
        Technology(slug="postgresql", name="PostgreSQL", category="Data & Analytics", description="PostgreSQL is the world's most advanced open-source relational database.", difficulty="Intermediate", learning_time="3-6 months", prerequisites=["SQL basics", "Database concepts"], skills=["Schema design", "Query optimization", "Indexing strategies", "Replication", "Extensions (PostGIS)"], applications=["Web apps", "Data warehousing", "Geospatial apps", "Analytics", "Enterprise systems"], companies=["Apple", "Meta", "Netflix", "Reddit", "Spotify"], future_outlook="Growing", growth_rate=82, popularity=90, icon="", color="#336791"),
        Technology(slug="redis", name="Redis", category="Infrastructure", description="Redis is an in-memory data store used for caching, real-time analytics, and message brokering.", difficulty="Intermediate", learning_time="1-2 months", prerequisites=["Basic data structures"], skills=["Data types", "Caching patterns", "Pub/Sub", "Persistence", "Cluster mode"], applications=["Caching", "Session storage", "Real-time analytics", "Message queues", "Rate limiting"], companies=["Twitter", "GitHub", "Snapchat", "Stack Overflow", "Uber"], future_outlook="Growing", growth_rate=78, popularity=86, icon="", color="#DC382D"),
        Technology(slug="nginx", name="Nginx", category="Infrastructure", description="Nginx is a high-performance web server, reverse proxy, and load balancer.", difficulty="Intermediate", learning_time="1-2 months", prerequisites=["Networking basics", "Linux"], skills=["Server blocks", "Reverse proxy", "Load balancing", "SSL/TLS", "Caching"], applications=["Web serving", "Reverse proxy", "API gateway", "Load balancing", "Static file serving"], companies=["Netflix", "Cloudflare", "Airbnb", "WordPress", "GitHub"], future_outlook="Stable", growth_rate=70, popularity=82, icon="", color="#009639"),
        Technology(slug="fastapi", name="FastAPI", category="Backend Development", description="FastAPI is a modern Python web framework for building APIs with automatic OpenAPI documentation.", difficulty="Intermediate", learning_time="2-3 months", prerequisites=["Python", "API concepts"], skills=["Route handling", "Pydantic models", "Dependency injection", "Async endpoints", "OpenAPI docs"], applications=["REST APIs", "Microservices", "Real-time apps", "ML model serving", "WebSocket apps"], companies=["Uber", "Netflix", "Microsoft", "Amazon", "Airbnb"], future_outlook="Growing", growth_rate=91, popularity=83, icon="", color="#009688"),
        Technology(slug="tensorflow", name="TensorFlow", category="Artificial Intelligence", description="TensorFlow is Google's end-to-end open-source ML platform.", difficulty="Advanced", learning_time="6-12 months", prerequisites=["Python", "Machine learning", "Linear algebra"], skills=["Keras API", "Model building", "TF Serving", "Distributed training", "TFLite"], applications=["Deep learning", "Production ML", "Mobile ML", "NLP", "Computer vision"], companies=["Google", "Airbnb", "Uber", "Snapchat", "Twitter"], future_outlook="Growing", growth_rate=85, popularity=84, icon="", color="#FF6F00"),
        Technology(slug="pytorch", name="PyTorch", category="Artificial Intelligence", description="PyTorch is Meta's deep learning framework with dynamic computation graphs.", difficulty="Advanced", learning_time="6-12 months", prerequisites=["Python", "Deep learning", "NumPy"], skills=["Tensors", "Autograd", "nn.Module", "DataLoaders", "TorchScript"], applications=["Research", "Computer vision", "NLP", "Generative models", "Reinforcement learning"], companies=["Meta", "OpenAI", "Tesla", "DeepMind", "Microsoft"], future_outlook="Growing", growth_rate=93, popularity=89, icon="", color="#EE4C2C"),
    ]

    tech_map = {}
    for t in techs:
        db.add(t); db.flush()
        tech_map[t.slug] = t
    db.commit()

    rels = [
        ("python", "machine-learning", "prerequisite", 9), ("python", "deep-learning", "prerequisite", 9),
        ("python", "data-science", "foundation", 10), ("python", "nlp", "prerequisite", 8),
        ("python", "computer-vision", "prerequisite", 8), ("python", "mlops", "prerequisite", 7),
        ("javascript", "typescript", "superset", 9), ("javascript", "react", "foundation", 10),
        ("javascript", "nodejs", "runtime", 9), ("typescript", "react", "enhances", 8),
        ("react", "nodejs", "complement", 7), ("machine-learning", "deep-learning", "prerequisite", 9),
        ("machine-learning", "mlops", "complement", 8), ("machine-learning", "data-science", "core", 9),
        ("machine-learning", "nlp", "foundation", 8), ("deep-learning", "computer-vision", "foundation", 9),
        ("deep-learning", "nlp", "foundation", 9), ("deep-learning", "llm-engineering", "prerequisite", 9),
        ("deep-learning", "tensorflow", "framework", 9), ("deep-learning", "pytorch", "framework", 9),
        ("nlp", "llm-engineering", "foundation", 9), ("nlp", "rag", "foundation", 8),
        ("llm-engineering", "rag", "enhances", 9), ("llm-engineering", "prompt-engineering", "extends", 8),
        ("rag", "prompt-engineering", "complement", 7), ("sql", "postgresql", "language", 9),
        ("sql", "data-science", "tool", 8), ("docker", "kubernetes", "prerequisite", 9),
        ("docker", "mlops", "tool", 7), ("kubernetes", "mlops", "platform", 8),
        ("kubernetes", "cloud-fundamentals", "extends", 7), ("aws", "cloud-fundamentals", "platform", 9),
        ("aws", "mlops", "infrastructure", 7), ("tensorflow", "pytorch", "alternative", 6),
        ("statistics", "data-science", "foundation", 9), ("statistics", "machine-learning", "foundation", 8),
        ("linear-algebra", "machine-learning", "foundation", 8), ("linear-algebra", "deep-learning", "foundation", 8),
        ("calculus", "deep-learning", "foundation", 8), ("python", "fastapi", "framework", 9),
        ("nodejs", "react", "fullstack", 8), ("go", "docker", "tool", 6), ("cybersecurity", "cloud-fundamentals", "complement", 6),
    ]
    for s, t, typ, st in rels:
        if s in tech_map and t in tech_map:
            db.add(Relationship(source_id=tech_map[s].id, target_id=tech_map[t].id, type=typ, strength=st))
    db.commit()

    careers = [
        Career(title="Machine Learning Engineer", description="Design and implement ML systems, build pipelines, and deploy models to production.",
               demand="Very High", salary_range="$120k-$200k", skills=["Python", "Machine Learning", "Deep Learning", "MLOps", "SQL", "Statistics", "Docker"],
               learning_order=["python", "statistics", "linear-algebra", "sql", "machine-learning", "deep-learning", "docker", "mlops", "pytorch"],
               projects=[{"name": "End-to-end ML Pipeline", "description": "Build a complete ML pipeline"}], estimated_time="12-18 months", growth="Very High"),
        Career(title="Full-Stack Developer", description="Build and maintain web applications across the entire stack.",
               demand="Very High", salary_range="$90k-$160k", skills=["JavaScript", "TypeScript", "React", "Node.js", "SQL", "Git", "Docker", "Cloud"],
               learning_order=["javascript", "git", "sql", "typescript", "react", "nodejs", "docker", "cloud-fundamentals"],
               projects=[{"name": "Full-stack Web App", "description": "Build a complete web application"}], estimated_time="6-12 months", growth="High"),
        Career(title="Data Scientist", description="Analyze complex data sets to drive business decisions.",
               demand="High", salary_range="$100k-$170k", skills=["Python", "SQL", "Statistics", "Machine Learning", "Data Visualization", "Big Data"],
               learning_order=["python", "statistics", "sql", "linear-algebra", "data-science", "machine-learning"],
               projects=[{"name": "Predictive Analytics", "description": "Build a model to predict business outcomes"}], estimated_time="6-12 months", growth="High"),
        Career(title="AI/ML Research Engineer", description="Push the boundaries of AI through research and development.",
               demand="High", salary_range="$140k-$250k", skills=["Python", "Deep Learning", "NLP", "Computer Vision", "PyTorch", "Transformers", "Calculus"],
               learning_order=["python", "calculus", "linear-algebra", "statistics", "machine-learning", "deep-learning", "nlp", "computer-vision", "pytorch", "llm-engineering"],
               projects=[{"name": "Research Reproduction", "description": "Reproduce a recent AI research paper"}], estimated_time="12-24 months", growth="Very High"),
        Career(title="Cloud Architect", description="Design and manage cloud infrastructure.",
               demand="High", salary_range="$130k-$200k", skills=["Cloud Computing", "AWS", "Docker", "Kubernetes", "Security", "Networking"],
               learning_order=["cloud-fundamentals", "docker", "kubernetes", "aws", "cybersecurity"],
               projects=[{"name": "Multi-tier Architecture", "description": "Design a scalable cloud architecture"}], estimated_time="12-18 months", growth="High"),
        Career(title="Cybersecurity Analyst", description="Protect organizational assets from cyber threats.",
               demand="Very High", salary_range="$90k-$160k", skills=["Cybersecurity", "Network Security", "Cloud Security", "Scripting", "Risk Assessment"],
               learning_order=["python", "cloud-fundamentals", "cybersecurity", "aws"],
               projects=[{"name": "Security Audit", "description": "Conduct a comprehensive security audit"}], estimated_time="6-12 months", growth="Very High"),
        Career(title="DevOps Engineer", description="Bridge development and operations with automation and CI/CD.",
               demand="High", salary_range="$110k-$180k", skills=["Docker", "Kubernetes", "CI/CD", "Cloud", "Linux", "Git", "Scripting"],
               learning_order=["git", "python", "docker", "cloud-fundamentals", "kubernetes", "mlops"],
               projects=[{"name": "CI/CD Pipeline", "description": "Build a complete CI/CD pipeline"}], estimated_time="6-12 months", growth="High"),
    ]
    for c in careers:
        db.add(c)
    db.commit()

    trends = [
        Trend(name="Large Language Models", category="AI", growth=98.5, momentum="Accelerating", stage="Growth", description="LLMs like GPT-4, Claude, and LLaMA are transforming AI interaction."),
        Trend(name="RAG Architectures", category="AI", growth=95.0, momentum="Accelerating", stage="Growth", description="RAG is the standard for production LLM applications."),
        Trend(name="AI Agents", category="AI", growth=92.0, momentum="Accelerating", stage="Emerging", description="Autonomous AI agents are the next frontier."),
        Trend(name="Edge AI", category="AI", growth=88.0, momentum="Growing", stage="Growth", description="Running AI models on edge devices."),
        Trend(name="MLOps", category="DevOps", growth=90.0, momentum="Growing", stage="Growth", description="MLOps brings DevOps practices to ML workflows."),
        Trend(name="Platform Engineering", category="DevOps", growth=85.0, momentum="Growing", stage="Growth", description="Building internal developer platforms."),
        Trend(name="WebAssembly", category="Web", growth=82.0, momentum="Growing", stage="Growth", description="High-performance code in the browser."),
        Trend(name="Serverless Computing", category="Cloud", growth=80.0, momentum="Stable", stage="Mature", description="Serverless continues to evolve."),
        Trend(name="Zero Trust Security", category="Security", growth=88.0, momentum="Growing", stage="Growth", description="Security model verifying every access request."),
        Trend(name="Quantum Computing", category="Computing", growth=75.0, momentum="Growing", stage="Emerging", description="Quantum computing advances."),
        Trend(name="Web3/Blockchain", category="Web", growth=45.0, momentum="Declining", stage="Declining", description="Web3 interest has declined."),
        Trend(name="Low-Code/No-Code", category="Development", growth=70.0, momentum="Stable", stage="Mature", description="Low-code platforms continue growing."),
        Trend(name="Data Mesh", category="Data", growth=78.0, momentum="Growing", stage="Growth", description="Decentralized data architecture."),
        Trend(name="Green Computing", category="Infrastructure", growth=72.0, momentum="Growing", stage="Growth", description="Sustainable computing practices."),
        Trend(name="Synthetic Data", category="AI", growth=85.0, momentum="Growing", stage="Emerging", description="AI-generated synthetic data for training."),
    ]
    for t in trends:
        db.add(t)
    db.commit()

    papers = [
        ResearchPaper(title="Attention Is All You Need", summary="Introduced the Transformer architecture for modern LLMs.", technologies=["deep-learning", "nlp", "llm-engineering"], concepts=["Self-attention", "Multi-head attention", "Transformer"], difficulty="Advanced"),
        ResearchPaper(title="BERT: Pre-training of Deep Bidirectional Transformers", summary="Introduced BERT for NLP benchmarks.", technologies=["nlp", "deep-learning", "llm-engineering"], concepts=["Masked language modeling", "Fine-tuning"], difficulty="Advanced"),
        ResearchPaper(title="Deep Residual Learning for Image Recognition", summary="Introduced ResNet with skip connections.", technologies=["deep-learning", "computer-vision", "pytorch"], concepts=["Residual connections", "Deep networks"], difficulty="Advanced"),
        ResearchPaper(title="Scaling Laws for Neural Language Models", summary="Showed model performance improves predictably with scale.", technologies=["llm-engineering", "nlp", "deep-learning"], concepts=["Scaling laws", "Emergent abilities"], difficulty="Intermediate"),
        ResearchPaper(title="Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks", summary="Introduced RAG architecture.", technologies=["rag", "llm-engineering", "nlp"], concepts=["Dense retrieval", "Knowledge grounding"], difficulty="Intermediate"),
    ]
    for p in papers:
        db.add(p)
    db.commit()
