from sqlalchemy.orm import Session
from app.models.models import User, Technology, Relationship, Career, Trend, ResearchPaper
from app.core.security import get_password_hash


def seed_database(db: Session):
    if db.query(Technology).count() > 0:
        return

    admin = User(username="admin", email="admin@atin.com", hashed_password=get_password_hash("admin123"), is_active=True, is_admin=True)
    db.add(admin); db.commit()

    technologies_data = [
        {"slug": "python", "name": "Python", "category": "Programming Languages",
         "description": "Python is a versatile, high-level programming language known for its readability and extensive ecosystem. It dominates AI/ML, data science, and backend development with frameworks like Django and FastAPI.",
         "difficulty": "Beginner", "learning_time": "2-3 months", "prerequisites": ["Basic computer literacy"],
         "skills": ["Syntax & fundamentals", "OOP", "Libraries (NumPy, Pandas)", "Web frameworks", "Testing"],
         "applications": ["Web development", "Data science", "Machine learning", "Automation", "Scripting"],
         "companies": ["Google", "Meta", "Netflix", "Spotify", "Instagram"],
         "future_outlook": "Growing", "growth_rate": 95, "popularity": 98, "icon": "", "color": "#3776AB"},
        {"slug": "javascript", "name": "JavaScript", "category": "Programming Languages",
         "description": "JavaScript is the language of the web, powering interactive frontends and scalable backends (Node.js). Essential for full-stack development with frameworks like React, Angular, and Vue.",
         "difficulty": "Beginner", "learning_time": "3-6 months", "prerequisites": ["Basic HTML/CSS"],
         "skills": ["ES6+ syntax", "DOM manipulation", "Async programming", "Frameworks (React/Vue)", "Node.js"],
         "applications": ["Web development", "Mobile apps (React Native)", "Desktop apps (Electron)", "Serverless functions", "Real-time apps"],
         "companies": ["Google", "Meta", "Microsoft", "Apple", "Amazon"],
         "future_outlook": "Growing", "growth_rate": 90, "popularity": 97, "icon": "", "color": "#F7DF1E"},
        {"slug": "typescript", "name": "TypeScript", "category": "Programming Languages",
         "description": "TypeScript adds static typing to JavaScript, catching errors at compile time. It's becoming the standard for large-scale applications and is heavily used in the Angular and React ecosystems.",
         "difficulty": "Intermediate", "learning_time": "3-6 months", "prerequisites": ["JavaScript"],
         "skills": ["Type system", "Generics", "Interfaces & types", "Decorators", "Module system"],
         "applications": ["Web apps", "Enterprise software", "Library development", "Full-stack development", "API development"],
         "companies": ["Microsoft", "Google", "Airbnb", "Asana", "Slack"],
         "future_outlook": "Growing", "growth_rate": 92, "popularity": 93, "icon": "", "color": "#3178C6"},
        {"slug": "react", "name": "React", "category": "Frontend Development",
         "description": "React is a declarative, component-based library for building user interfaces. With hooks, suspense, and server components, it remains the most popular frontend framework.",
         "difficulty": "Intermediate", "learning_time": "3-6 months", "prerequisites": ["JavaScript", "HTML/CSS"],
         "skills": ["Components & props", "Hooks", "State management", "Routing", "Performance optimization"],
         "applications": ["Single-page apps", "E-commerce platforms", "Social media", "Dashboard interfaces", "Mobile (React Native)"],
         "companies": ["Meta", "Netflix", "Airbnb", "Uber", "Twitter"],
         "future_outlook": "Growing", "growth_rate": 88, "popularity": 94, "icon": "", "color": "#61DAFB"},
        {"slug": "nodejs", "name": "Node.js", "category": "Backend Development",
         "description": "Node.js enables JavaScript on the server with event-driven, non-blocking I/O. It's the backbone of modern web APIs, microservices, and real-time applications.",
         "difficulty": "Intermediate", "learning_time": "3-6 months", "prerequisites": ["JavaScript"],
         "skills": ["Express.js", "RESTful APIs", "Middleware", "Database integration", "Authentication"],
         "applications": ["API servers", "Microservices", "Real-time apps", "CLI tools", "Web sockets"],
         "companies": ["LinkedIn", "Netflix", "PayPal", "Uber", "Walmart"],
         "future_outlook": "Growing", "growth_rate": 85, "popularity": 92, "icon": "", "color": "#339933"},
        {"slug": "machine-learning", "name": "Machine Learning", "category": "Artificial Intelligence",
         "description": "Machine Learning enables systems to learn and improve from experience. Covers supervised/unsupervised learning, feature engineering, model selection, and deployment.",
         "difficulty": "Advanced", "learning_time": "6-12 months", "prerequisites": ["Python", "Statistics", "Linear algebra"],
         "skills": ["Supervised learning", "Unsupervised learning", "Feature engineering", "Model evaluation", "Scikit-learn"],
         "applications": ["Recommendation systems", "Fraud detection", "Predictive analytics", "Image recognition", "Natural language processing"],
         "companies": ["Google", "Amazon", "Microsoft", "Apple", "Netflix"],
         "future_outlook": "Growing", "growth_rate": 98, "popularity": 95, "icon": "", "color": "#FF6F00"},
        {"slug": "deep-learning", "name": "Deep Learning", "category": "Artificial Intelligence",
         "description": "Deep Learning uses multi-layer neural networks to model complex patterns. Powers breakthroughs in computer vision, NLP, and generative AI with frameworks like PyTorch and TensorFlow.",
         "difficulty": "Advanced", "learning_time": "6-12 months", "prerequisites": ["Machine learning", "Python", "Calculus"],
         "skills": ["Neural networks", "CNNs", "RNNs/Transformers", "TensorFlow/PyTorch", "GPU optimization"],
         "applications": ["Computer vision", "Speech recognition", "Natural language processing", "Generative AI", "Autonomous vehicles"],
         "companies": ["Google DeepMind", "OpenAI", "Meta AI", "Tesla", "NVIDIA"],
         "future_outlook": "Growing", "growth_rate": 99, "popularity": 93, "icon": "", "color": "#E91E63"},
        {"slug": "llm-engineering", "name": "LLM Engineering", "category": "Artificial Intelligence",
         "description": "LLM Engineering covers the entire lifecycle of large language models: prompt engineering, fine-tuning, RAG architectures, vector databases, and LLMOps for production deployment.",
         "difficulty": "Advanced", "learning_time": "6-12 months", "prerequisites": ["Python", "Deep learning", "NLP basics"],
         "skills": ["Prompt engineering", "RAG architectures", "Vector databases", "Fine-tuning", "LLM evaluation"],
         "applications": ["Chatbots", "Code generation", "Content creation", "Document analysis", "Knowledge retrieval"],
         "companies": ["OpenAI", "Anthropic", "Google", "Microsoft", "Hugging Face"],
         "future_outlook": "Growing", "growth_rate": 100, "popularity": 96, "icon": "", "color": "#9C27B0"},
        {"slug": "nlp", "name": "Natural Language Processing", "category": "Artificial Intelligence",
         "description": "NLP enables computers to understand, interpret, and generate human language. From sentiment analysis to machine translation, it's a cornerstone of modern AI applications.",
         "difficulty": "Advanced", "learning_time": "6-12 months", "prerequisites": ["Python", "Machine learning", "Linguistics basics"],
         "skills": ["Text preprocessing", "Word embeddings", "Sequence models", "Transformers", "Hugging Face"],
         "applications": ["Sentiment analysis", "Machine translation", "Text summarization", "Named entity recognition", "Question answering"],
         "companies": ["Google", "Meta", "Amazon", "Microsoft", "OpenAI"],
         "future_outlook": "Growing", "growth_rate": 97, "popularity": 89, "icon": "", "color": "#4CAF50"},
        {"slug": "computer-vision", "name": "Computer Vision", "category": "Artificial Intelligence",
         "description": "Computer Vision enables machines to interpret visual information. Covers image classification, object detection, segmentation, and video analysis using CNNs and vision transformers.",
         "difficulty": "Advanced", "learning_time": "6-12 months", "prerequisites": ["Python", "Deep learning", "Linear algebra"],
         "skills": ["Image processing", "CNNs", "Object detection (YOLO)", "Image segmentation", "OpenCV"],
         "applications": ["Autonomous vehicles", "Medical imaging", "Surveillance", "AR/VR", "Quality inspection"],
         "companies": ["Tesla", "Google", "Meta", "NVIDIA", "Waymo"],
         "future_outlook": "Growing", "growth_rate": 94, "popularity": 87, "icon": "", "color": "#FF5722"},
        {"slug": "rag", "name": "RAG (Retrieval Augmented Generation)", "category": "Artificial Intelligence",
         "description": "RAG combines information retrieval with LLMs to generate accurate, context-aware responses. It reduces hallucinations and enables knowledge-grounded AI applications.",
         "difficulty": "Advanced", "learning_time": "3-6 months", "prerequisites": ["Python", "LLM basics", "Vector databases"],
         "skills": ["Document chunking", "Embeddings", "Vector search", "Retrieval pipelines", "Evaluation"],
         "applications": ["Enterprise search", "Customer support", "Document QA", "Knowledge bases", "Research assistants"],
         "companies": ["OpenAI", "Anthropic", "Cohere", "LlamaIndex", "LangChain"],
         "future_outlook": "Growing", "growth_rate": 98, "popularity": 88, "icon": "", "color": "#00BCD4"},
        {"slug": "prompt-engineering", "name": "Prompt Engineering", "category": "Artificial Intelligence",
         "description": "Prompt Engineering is the art of designing inputs to guide LLM outputs. Essential for getting reliable, structured results from language models in production applications.",
         "difficulty": "Beginner", "learning_time": "1-2 months", "prerequisites": ["Basic AI concepts"],
         "skills": ["Chain-of-thought", "Few-shot learning", "Structured outputs", "Context management", "Evaluation"],
         "applications": ["Content generation", "Code assistance", "Data extraction", "Chatbots", "Automation"],
         "companies": ["OpenAI", "Anthropic", "Google", "Microsoft", "GitHub"],
         "future_outlook": "Growing", "growth_rate": 96, "popularity": 85, "icon": "", "color": "#FFC107"},
        {"slug": "sql", "name": "SQL", "category": "Data & Analytics",
         "description": "SQL is the standard language for relational database management and data manipulation. Essential for backend development, data analysis, and business intelligence.",
         "difficulty": "Beginner", "learning_time": "1-3 months", "prerequisites": ["Basic data concepts"],
         "skills": ["SELECT queries", "JOINs", "Aggregations", "Indexing", "Normalization"],
         "applications": ["Data analysis", "Backend development", "Business intelligence", "Reporting", "ETL pipelines"],
         "companies": ["All tech companies"],
         "future_outlook": "Stable", "growth_rate": 80, "popularity": 93, "icon": "", "color": "#336791"},
        {"slug": "docker", "name": "Docker", "category": "DevOps & Cloud",
         "description": "Docker containers package applications with all dependencies, ensuring consistency across environments. The foundation of modern DevOps, CI/CD, and cloud-native development.",
         "difficulty": "Intermediate", "learning_time": "2-3 months", "prerequisites": ["Linux basics", "CLI familiarity"],
         "skills": ["Dockerfile syntax", "Image management", "Docker Compose", "Networking", "Registry management"],
         "applications": ["Microservices", "CI/CD pipelines", "Dev environments", "Cloud deployment", "Edge computing"],
         "companies": ["All tech companies"],
         "future_outlook": "Growing", "growth_rate": 88, "popularity": 92, "icon": "", "color": "#2496ED"},
        {"slug": "kubernetes", "name": "Kubernetes", "category": "DevOps & Cloud",
         "description": "Kubernetes orchestrates containerized applications at scale. The industry standard for container orchestration, service discovery, and automated deployment management.",
         "difficulty": "Advanced", "learning_time": "3-6 months", "prerequisites": ["Docker", "Networking", "Linux"],
         "skills": ["Pods & deployments", "Services & ingress", "Helm charts", "RBAC", "Cluster management"],
         "applications": ["Container orchestration", "Cloud-native apps", "Microservices", "Auto-scaling", "Service mesh"],
         "companies": ["Google", "Amazon", "Microsoft", "Spotify", "Uber"],
         "future_outlook": "Growing", "growth_rate": 90, "popularity": 90, "icon": "", "color": "#326CE5"},
        {"slug": "aws", "name": "AWS", "category": "DevOps & Cloud",
         "description": "Amazon Web Services is the leading cloud platform with 200+ services. From EC2 to SageMaker, it provides the infrastructure backbone for modern applications.",
         "difficulty": "Intermediate", "learning_time": "6-12 months", "prerequisites": ["Networking", "Linux basics"],
         "skills": ["EC2 & S3", "Lambda", "RDS & DynamoDB", "IAM & security", "Cloud architecture"],
         "applications": ["Cloud hosting", "Serverless apps", "Data lakes", "Machine learning", "IoT"],
         "companies": ["Netflix", "Airbnb", "Lyft", "Slack", "Pinterest"],
         "future_outlook": "Growing", "growth_rate": 87, "popularity": 95, "icon": "", "color": "#FF9900"},
        {"slug": "cloud-fundamentals", "name": "Cloud Computing", "category": "DevOps & Cloud",
         "description": "Cloud Computing fundamentals cover IaaS, PaaS, SaaS models, deployment strategies, and cloud architecture patterns essential for modern software development.",
         "difficulty": "Intermediate", "learning_time": "3-6 months", "prerequisites": ["Networking basics"],
         "skills": ["Cloud models", "Virtualization", "Storage solutions", "Networking", "Security & compliance"],
         "applications": ["Infrastructure hosting", "Disaster recovery", "DevOps", "Big data", "AI/ML workloads"],
         "companies": ["All cloud providers"],
         "future_outlook": "Growing", "growth_rate": 85, "popularity": 94, "icon": "", "color": "#4285F4"},
        {"slug": "git", "name": "Git", "category": "DevOps & Cloud",
         "description": "Git is the industry-standard version control system. Essential for collaboration, code management, and CI/CD workflows in any software project.",
         "difficulty": "Beginner", "learning_time": "1-2 months", "prerequisites": ["CLI basics"],
         "skills": ["Branching & merging", "Rebasing", "Pull requests", "Git workflows", "Conflict resolution"],
         "applications": ["Version control", "Collaboration", "CI/CD", "Open source", "Code review"],
         "companies": ["All tech companies"],
         "future_outlook": "Stable", "growth_rate": 75, "popularity": 96, "icon": "", "color": "#F05032"},
        {"slug": "mlops", "name": "MLOps", "category": "DevOps & Cloud",
         "description": "MLOps applies DevOps principles to machine learning. Covers experiment tracking, model versioning, CI/CD for ML pipelines, model serving, monitoring, and governance.",
         "difficulty": "Advanced", "learning_time": "3-6 months", "prerequisites": ["Machine learning", "DevOps", "Docker"],
         "skills": ["MLflow", "Model serving", "Feature stores", "Pipeline automation", "Model monitoring"],
         "applications": ["ML production", "Model governance", "A/B testing", "Model registry", "Automated retraining"],
         "companies": ["Google", "Netflix", "Uber", "Airbnb", "Microsoft"],
         "future_outlook": "Growing", "growth_rate": 95, "popularity": 82, "icon": "", "color": "#00BFA5"},
        {"slug": "cybersecurity", "name": "Cybersecurity", "category": "Security",
         "description": "Cybersecurity protects systems, networks, and data from digital attacks. Covers network security, cryptography, ethical hacking, and security operations.",
         "difficulty": "Advanced", "learning_time": "6-12 months", "prerequisites": ["Networking", "Operating systems"],
         "skills": ["Network security", "Cryptography", "Penetration testing", "Security analysis", "Incident response"],
         "applications": ["Network protection", "Data encryption", "Threat detection", "Compliance", "Security auditing"],
         "companies": ["CrowdStrike", "Palo Alto Networks", "Cloudflare", "Microsoft", "Google"],
         "future_outlook": "Growing", "growth_rate": 96, "popularity": 91, "icon": "", "color": "#DC2626"},
        {"slug": "data-science", "name": "Data Science", "category": "Data & Analytics",
         "description": "Data Science combines statistics, programming, and domain expertise to extract insights from data. Essential for data-driven decision making across industries.",
         "difficulty": "Intermediate", "learning_time": "6-12 months", "prerequisites": ["Python", "Statistics", "SQL"],
         "skills": ["Statistical analysis", "Data visualization", "Machine learning", "Big data tools", "Storytelling"],
         "applications": ["Business intelligence", "Predictive modeling", "Customer analytics", "Risk assessment", "Optimization"],
         "companies": ["Google", "Amazon", "Netflix", "Spotify", "Airbnb"],
         "future_outlook": "Growing", "growth_rate": 87, "popularity": 88, "icon": "", "color": "#1A237E"},
        {"slug": "statistics", "name": "Statistics", "category": "Mathematics",
         "description": "Statistics provides the mathematical foundation for data analysis and machine learning. Covers probability, hypothesis testing, regression, and experimental design.",
         "difficulty": "Intermediate", "learning_time": "3-6 months", "prerequisites": ["Basic mathematics"],
         "skills": ["Probability", "Hypothesis testing", "Regression", "Bayesian methods", "Experimental design"],
         "applications": ["Data analysis", "A/B testing", "Research", "Quality control", "Risk modeling"],
         "companies": ["All data-driven companies"],
         "future_outlook": "Stable", "growth_rate": 72, "popularity": 80, "icon": "", "color": "#3949AB"},
        {"slug": "linear-algebra", "name": "Linear Algebra", "category": "Mathematics",
         "description": "Linear Algebra is fundamental to machine learning and deep learning. Covers vectors, matrices, eigenvalues, and transformations that power neural networks.",
         "difficulty": "Intermediate", "learning_time": "2-3 months", "prerequisites": ["High school math"],
         "skills": ["Vectors & matrices", "Matrix operations", "Eigenvalues", "Vector spaces", "Linear transformations"],
         "applications": ["Machine learning", "Computer graphics", "Quantum computing", "Data science", "Optimization"],
         "companies": ["NVIDIA", "Google", "Meta", "DeepMind", "Intel"],
         "future_outlook": "Stable", "growth_rate": 70, "popularity": 75, "icon": "", "color": "#5E35B1"},
        {"slug": "calculus", "name": "Calculus", "category": "Mathematics",
         "description": "Calculus provides the mathematical foundation for optimization in machine learning. Derivatives and gradients drive the backpropagation algorithm in neural networks.",
         "difficulty": "Intermediate", "learning_time": "2-3 months", "prerequisites": ["High school math"],
         "skills": ["Derivatives", "Integrals", "Multivariable calculus", "Gradients", "Optimization"],
         "applications": ["Deep learning", "Physics simulations", "Economics", "Engineering", "Optimization"],
         "companies": ["NVIDIA", "Google", "Meta", "DeepMind", "Intel"],
         "future_outlook": "Stable", "growth_rate": 65, "popularity": 68, "icon": "", "color": "#8E24AA"},
        {"slug": "rust", "name": "Rust", "category": "Programming Languages",
         "description": "Rust is a systems programming language focused on safety, speed, and concurrency. It's increasingly used for performance-critical applications and as a safer C++ alternative.",
         "difficulty": "Advanced", "learning_time": "6-12 months", "prerequisites": ["C/C++ basics", "Systems programming"],
         "skills": ["Ownership & borrowing", "Lifetimes", "Traits", "Concurrency", "Unsafe Rust"],
         "applications": ["Systems programming", "WebAssembly", "CLI tools", "Embedded systems", "Game engines"],
         "companies": ["Mozilla", "Microsoft", "Google", "Amazon", "Meta"],
         "future_outlook": "Growing", "growth_rate": 85, "popularity": 78, "icon": "", "color": "#DEA584"},
        {"slug": "go", "name": "Go", "category": "Programming Languages",
         "description": "Go (Golang) is a statically typed, compiled language designed for simplicity and concurrency. Popular for cloud services, microservices, and CLI tools.",
         "difficulty": "Intermediate", "learning_time": "3-6 months", "prerequisites": ["Programming basics"],
         "skills": ["Concurrency (goroutines)", "Interfaces", "Error handling", "Standard library", "Testing"],
         "applications": ["Cloud services", "Microservices", "CLI tools", "DevOps tools", "Network servers"],
         "companies": ["Google", "Uber", "Twitch", "Dropbox", "Cloudflare"],
         "future_outlook": "Growing", "growth_rate": 84, "popularity": 81, "icon": "", "color": "#00ADD8"},
        {"slug": "postgresql", "name": "PostgreSQL", "category": "Data & Analytics",
         "description": "PostgreSQL is the world's most advanced open-source relational database. Known for reliability, feature richness, and extensibility with support for JSON, full-text search, and custom types.",
         "difficulty": "Intermediate", "learning_time": "3-6 months", "prerequisites": ["SQL basics", "Database concepts"],
         "skills": ["Schema design", "Query optimization", "Indexing strategies", "Replication", "Extensions (PostGIS)"],
         "applications": ["Web apps", "Data warehousing", "Geospatial apps", "Analytics", "Enterprise systems"],
         "companies": ["Apple", "Meta", "Netflix", "Reddit", "Spotify"],
         "future_outlook": "Growing", "growth_rate": 82, "popularity": 90, "icon": "", "color": "#336791"},
        {"slug": "redis", "name": "Redis", "category": "Infrastructure",
         "description": "Redis is an in-memory data store used for caching, real-time analytics, message brokering, and session management. It's the most popular key-value store in production.",
         "difficulty": "Intermediate", "learning_time": "1-2 months", "prerequisites": ["Basic data structures"],
         "skills": ["Data types", "Caching patterns", "Pub/Sub", "Persistence", "Cluster mode"],
         "applications": ["Caching", "Session storage", "Real-time analytics", "Message queues", "Rate limiting"],
         "companies": ["Twitter", "GitHub", "Snapchat", "Stack Overflow", "Uber"],
         "future_outlook": "Growing", "growth_rate": 78, "popularity": 86, "icon": "", "color": "#DC382D"},
        {"slug": "nginx", "name": "Nginx", "category": "Infrastructure",
         "description": "Nginx is a high-performance web server, reverse proxy, and load balancer. It's the standard for serving static content and routing traffic in modern web architectures.",
         "difficulty": "Intermediate", "learning_time": "1-2 months", "prerequisites": ["Networking basics", "Linux"],
         "skills": ["Server blocks", "Reverse proxy", "Load balancing", "SSL/TLS", "Caching"],
         "applications": ["Web serving", "Reverse proxy", "API gateway", "Load balancing", "Static file serving"],
         "companies": ["Netflix", "Cloudflare", "Airbnb", "WordPress", "GitHub"],
         "future_outlook": "Stable", "growth_rate": 70, "popularity": 82, "icon": "", "color": "#009639"},
        {"slug": "fastapi", "name": "FastAPI", "category": "Backend Development",
         "description": "FastAPI is a modern Python web framework for building APIs with automatic OpenAPI documentation, type validation, and async support. It's among the fastest-growing backend frameworks.",
         "difficulty": "Intermediate", "learning_time": "2-3 months", "prerequisites": ["Python", "API concepts"],
         "skills": ["Route handling", "Pydantic models", "Dependency injection", "Async endpoints", "OpenAPI docs"],
         "applications": ["REST APIs", "Microservices", "Real-time apps", "ML model serving", "WebSocket apps"],
         "companies": ["Uber", "Netflix", "Microsoft", "Amazon", "Airbnb"],
         "future_outlook": "Growing", "growth_rate": 91, "popularity": 83, "icon": "", "color": "#009688"},
        {"slug": "tensorflow", "name": "TensorFlow", "category": "Artificial Intelligence",
         "description": "TensorFlow is Google's end-to-end open-source ML platform. It provides a comprehensive ecosystem for building, training, and deploying machine learning models at scale.",
         "difficulty": "Advanced", "learning_time": "6-12 months", "prerequisites": ["Python", "Machine learning", "Linear algebra"],
         "skills": ["Keras API", "Model building", "TF Serving", "Distributed training", "TFLite"],
         "applications": ["Deep learning", "Production ML", "Mobile ML", "NLP", "Computer vision"],
         "companies": ["Google", "Airbnb", "Uber", "Snapchat", "Twitter"],
         "future_outlook": "Growing", "growth_rate": 85, "popularity": 84, "icon": "", "color": "#FF6F00"},
        {"slug": "pytorch", "name": "PyTorch", "category": "Artificial Intelligence",
         "description": "PyTorch is Meta's deep learning framework with dynamic computation graphs. It's the preferred framework for research and production AI due to its flexibility and Pythonic design.",
         "difficulty": "Advanced", "learning_time": "6-12 months", "prerequisites": ["Python", "Deep learning", "NumPy"],
         "skills": ["Tensors", "Autograd", "nn.Module", "DataLoaders", "TorchScript"],
         "applications": ["Research", "Computer vision", "NLP", "Generative models", "Reinforcement learning"],
         "companies": ["Meta", "OpenAI", "Tesla", "DeepMind", "Microsoft"],
         "future_outlook": "Growing", "growth_rate": 93, "popularity": 89, "icon": "", "color": "#EE4C2C"},
    ]

    tech_objects = {}
    for td in technologies_data:
        tech = Technology(**td)
        db.add(tech); db.flush()
        tech_objects[tech.slug] = tech
    db.commit()

    relationships_data = [
        ("python", "machine-learning", "prerequisite", 9), ("python", "deep-learning", "prerequisite", 9),
        ("python", "data-science", "foundation", 10), ("python", "nlp", "prerequisite", 8),
        ("python", "computer-vision", "prerequisite", 8), ("python", "mlops", "prerequisite", 7),
        ("javascript", "typescript", "superset", 9), ("javascript", "react", "foundation", 10),
        ("javascript", "nodejs", "runtime", 9), ("typescript", "react", "enhances", 8),
        ("react", "nodejs", "complement", 7), ("machine-learning", "deep-learning", "prerequisite", 9),
        ("machine-learning", "mlops", "complement", 8), ("machine-learning", "data-science", "core", 9),
        ("machine-learning", "nlp", "foundation", 8), ("deep-learning", "computer-vision", "foundation", 9),
        ("deep-learning", "nlp", "foundation", 9), ("deep-learning", "llm-engineering", "prerequisite", 9),
        ("deep-learning", "tensorflow", "framework", 9), ("deep-learning", "pytorch", "framework", 9),
        ("nlp", "llm-engineering", "foundation", 9), ("nlp", "rag", "foundation", 8),
        ("llm-engineering", "rag", "enhances", 9), ("llm-engineering", "prompt-engineering", "extends", 8),
        ("rag", "prompt-engineering", "complement", 7), ("sql", "postgresql", "language", 9),
        ("sql", "data-science", "tool", 8), ("docker", "kubernetes", "prerequisite", 9),
        ("docker", "mlops", "tool", 7), ("kubernetes", "mlops", "platform", 8),
        ("kubernetes", "cloud-fundamentals", "extends", 7), ("aws", "cloud-fundamentals", "platform", 9),
        ("aws", "mlops", "infrastructure", 7), ("tensorflow", "pytorch", "alternative", 6),
        ("tensorflow", "mlops", "complement", 6), ("pytorch", "mlops", "complement", 6),
        ("statistics", "data-science", "foundation", 9), ("statistics", "machine-learning", "foundation", 8),
        ("linear-algebra", "machine-learning", "foundation", 8), ("linear-algebra", "deep-learning", "foundation", 8),
        ("calculus", "deep-learning", "foundation", 8), ("calculus", "machine-learning", "foundation", 7),
        ("cybersecurity", "cloud-fundamentals", "complement", 6), ("python", "fastapi", "framework", 9),
        ("nodejs", "react", "fullstack", 8), ("go", "docker", "tool", 6), ("rust", "computer-vision", "performance", 5),
    ]

    for src, tgt, typ, strength in relationships_data:
        if src in tech_objects and tgt in tech_objects:
            db.add(Relationship(source_id=tech_objects[src].id, target_id=tech_objects[tgt].id, type=typ, strength=strength))
    db.commit()

    careers_data = [
        {"title": "Machine Learning Engineer", "description": "Design and implement ML systems, build pipelines, and deploy models to production.",
         "demand": "Very High", "salary_range": "$120k-$200k",
         "skills": ["Python", "Machine Learning", "Deep Learning", "MLOps", "SQL", "Statistics", "Docker"],
         "learning_order": ["python", "statistics", "linear-algebra", "sql", "machine-learning", "deep-learning", "docker", "mlops", "pytorch"],
         "projects": [{"name": "End-to-end ML Pipeline", "description": "Build a complete ML pipeline from data collection to model deployment"},
                       {"name": "Real-time Prediction API", "description": "Deploy a model as a REST API with monitoring"},
                       {"name": "ML Model Registry", "description": "Implement model versioning and A/B testing infrastructure"}],
         "estimated_time": "12-18 months", "growth": "Very High"},
        {"title": "Full-Stack Developer", "description": "Build and maintain web applications across the entire stack.",
         "demand": "Very High", "salary_range": "$90k-$160k",
         "skills": ["JavaScript", "TypeScript", "React", "Node.js", "SQL", "Git", "Docker", "Cloud"],
         "learning_order": ["javascript", "git", "sql", "typescript", "react", "nodejs", "docker", "cloud-fundamentals"],
         "projects": [{"name": "Full-stack Web App", "description": "Build a complete web application with auth, database, and deployment"},
                       {"name": "REST API Design", "description": "Design and implement a production-grade RESTful API"},
                       {"name": "Real-time Dashboard", "description": "Build a real-time data dashboard with WebSockets"}],
         "estimated_time": "6-12 months", "growth": "High"},
        {"title": "Data Scientist", "description": "Analyze complex data sets to drive business decisions.",
         "demand": "High", "salary_range": "$100k-$170k",
         "skills": ["Python", "SQL", "Statistics", "Machine Learning", "Data Visualization", "Big Data"],
         "learning_order": ["python", "statistics", "sql", "linear-algebra", "data-science", "machine-learning"],
         "projects": [{"name": "Predictive Analytics", "description": "Build a model to predict business outcomes from historical data"},
                       {"name": "A/B Testing Framework", "description": "Design and analyze an A/B testing experiment"},
                       {"name": "Data Pipeline", "description": "Create an ETL pipeline for business intelligence"}],
         "estimated_time": "6-12 months", "growth": "High"},
        {"title": "AI/ML Research Engineer", "description": "Push the boundaries of AI through research and development.",
         "demand": "High", "salary_range": "$140k-$250k",
         "skills": ["Python", "Deep Learning", "NLP", "Computer Vision", "PyTorch", "Transformers", "Calculus"],
         "learning_order": ["python", "calculus", "linear-algebra", "statistics", "machine-learning", "deep-learning", "nlp", "computer-vision", "pytorch", "llm-engineering"],
         "projects": [{"name": "Research Reproduction", "description": "Reproduce a recent AI research paper and evaluate results"},
                       {"name": "Custom Model Architecture", "description": "Design and train a novel neural network architecture"},
                       {"name": "LLM Fine-tuning", "description": "Fine-tune a large language model for a specific domain"}],
         "estimated_time": "12-24 months", "growth": "Very High"},
        {"title": "Cloud Architect", "description": "Design and manage cloud infrastructure.",
         "demand": "High", "salary_range": "$130k-$200k",
         "skills": ["Cloud Computing", "AWS", "Docker", "Kubernetes", "Security", "Networking", "Terraform"],
         "learning_order": ["cloud-fundamentals", "docker", "kubernetes", "aws", "cybersecurity"],
         "projects": [{"name": "Multi-tier Architecture", "description": "Design a scalable, secure cloud architecture"},
                       {"name": "Kubernetes Cluster", "description": "Deploy and manage a production Kubernetes cluster"},
                       {"name": "Disaster Recovery", "description": "Implement multi-region disaster recovery solution"}],
         "estimated_time": "12-18 months", "growth": "High"},
        {"title": "Cybersecurity Analyst", "description": "Protect organizational assets from cyber threats.",
         "demand": "Very High", "salary_range": "$90k-$160k",
         "skills": ["Cybersecurity", "Network Security", "Cloud Security", "Scripting", "Risk Assessment"],
         "learning_order": ["python", "cloud-fundamentals", "cybersecurity", "aws"],
         "projects": [{"name": "Security Audit", "description": "Conduct a comprehensive security audit of a system"},
                       {"name": "Incident Response Plan", "description": "Develop an incident response playbook"},
                       {"name": "Security Scanner", "description": "Build a vulnerability scanning tool"}],
         "estimated_time": "6-12 months", "growth": "Very High"},
        {"title": "DevOps Engineer", "description": "Bridge development and operations.",
         "demand": "High", "salary_range": "$110k-$180k",
         "skills": ["Docker", "Kubernetes", "CI/CD", "Cloud", "Linux", "Git", "Scripting"],
         "learning_order": ["git", "python", "docker", "cloud-fundamentals", "kubernetes", "mlops"],
         "projects": [{"name": "CI/CD Pipeline", "description": "Build a complete CI/CD pipeline with automated testing"},
                       {"name": "Infrastructure as Code", "description": "Implement infrastructure management with Terraform"},
                       {"name": "Monitoring Stack", "description": "Deploy a comprehensive monitoring and alerting system"}],
         "estimated_time": "6-12 months", "growth": "High"},
    ]
    for cd in careers_data:
        db.add(Career(**cd))
    db.commit()

    trends_data = [
        {"name": "Large Language Models", "category": "AI", "growth": 98.5, "momentum": "Accelerating", "stage": "Growth", "description": "LLMs like GPT-4, Claude, and LLaMA are transforming how we interact with AI."},
        {"name": "RAG Architectures", "category": "AI", "growth": 95.0, "momentum": "Accelerating", "stage": "Growth", "description": "Retrieval Augmented Generation is the standard for production LLM applications."},
        {"name": "AI Agents", "category": "AI", "growth": 92.0, "momentum": "Accelerating", "stage": "Emerging", "description": "Autonomous AI agents are the next frontier in AI application development."},
        {"name": "Edge AI", "category": "AI", "growth": 88.0, "momentum": "Growing", "stage": "Growth", "description": "Running AI models on edge devices for low-latency inference."},
        {"name": "MLOps", "category": "DevOps", "growth": 90.0, "momentum": "Growing", "stage": "Growth", "description": "Machine learning operations brings DevOps practices to ML workflows."},
        {"name": "Platform Engineering", "category": "DevOps", "growth": 85.0, "momentum": "Growing", "stage": "Growth", "description": "Building internal developer platforms to streamline development workflows."},
        {"name": "WebAssembly", "category": "Web", "growth": 82.0, "momentum": "Growing", "stage": "Growth", "description": "Running high-performance code in the browser with near-native speed."},
        {"name": "Serverless Computing", "category": "Cloud", "growth": 80.0, "momentum": "Stable", "stage": "Mature", "description": "Serverless continues to evolve with longer runtimes and better tooling."},
        {"name": "Zero Trust Security", "category": "Security", "growth": 88.0, "momentum": "Growing", "stage": "Growth", "description": "Security model that requires verification for every access request."},
        {"name": "Quantum Computing", "category": "Computing", "growth": 75.0, "momentum": "Growing", "stage": "Emerging", "description": "Quantum computing advances toward practical applications in cryptography and optimization."},
        {"name": "Web3/Blockchain", "category": "Web", "growth": 45.0, "momentum": "Declining", "stage": "Declining", "description": "Web3 interest has declined as regulatory challenges and scalability issues persist."},
        {"name": "Low-Code/No-Code", "category": "Development", "growth": 70.0, "momentum": "Stable", "stage": "Mature", "description": "Low-code platforms continue to grow but at a slower pace."},
        {"name": "Data Mesh", "category": "Data", "growth": 78.0, "momentum": "Growing", "stage": "Growth", "description": "Decentralized data architecture pattern gaining enterprise adoption."},
        {"name": "Green Computing", "category": "Infrastructure", "growth": 72.0, "momentum": "Growing", "stage": "Growth", "description": "Sustainable computing practices and energy-efficient data centers."},
        {"name": "Synthetic Data", "category": "AI", "growth": 85.0, "momentum": "Growing", "stage": "Emerging", "description": "AI-generated synthetic data for training ML models while preserving privacy."},
    ]
    for td in trends_data:
        db.add(Trend(**td))
    db.commit()

    papers_data = [
        {"title": "Attention Is All You Need", "summary": "Introduced the Transformer architecture, which became the foundation for modern LLMs. The paper proposed a novel attention mechanism that replaced recurrence with self-attention.",
         "technologies": ["deep-learning", "nlp", "llm-engineering"], "concepts": ["Self-attention", "Multi-head attention", "Positional encoding", "Transformer"], "difficulty": "Advanced"},
        {"title": "BERT: Pre-training of Deep Bidirectional Transformers", "summary": "Introduced BERT (Bidirectional Encoder Representations from Transformers), which set new benchmarks on 11 NLP tasks.",
         "technologies": ["nlp", "deep-learning", "llm-engineering"], "concepts": ["Masked language modeling", "Next sentence prediction", "Bidirectional encoding", "Fine-tuning"], "difficulty": "Advanced"},
        {"title": "Deep Residual Learning for Image Recognition", "summary": "Introduced ResNet with skip connections that enabled training of very deep neural networks (152 layers).",
         "technologies": ["deep-learning", "computer-vision", "pytorch"], "concepts": ["Residual connections", "Batch normalization", "Deep networks", "Image classification"], "difficulty": "Advanced"},
        {"title": "Generative Adversarial Networks", "summary": "Introduced GANs where two networks (generator and discriminator) compete in a zero-sum game.",
         "technologies": ["deep-learning", "computer-vision", "pytorch"], "concepts": ["Adversarial training", "Generator network", "Discriminator network", "Latent space"], "difficulty": "Advanced"},
        {"title": "Scaling Laws for Neural Language Models", "summary": "Empirically showed that model performance improves predictably with scale (compute, data, parameters).",
         "technologies": ["llm-engineering", "nlp", "deep-learning"], "concepts": ["Scaling laws", "Power-law scaling", "Compute optimal training", "Emergent abilities"], "difficulty": "Intermediate"},
        {"title": "Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks", "summary": "Introduced the RAG architecture combining retrieval from a knowledge corpus with generative models.",
         "technologies": ["rag", "llm-engineering", "nlp"], "concepts": ["Dense retrieval", "Knowledge grounding", "Hybrid generation", "Hallucination reduction"], "difficulty": "Intermediate"},
    ]
    for pd in papers_data:
        db.add(ResearchPaper(**pd))
    db.commit()
